[settings]
auto_install = true
lockfile = true

[tools]
# Root
hk = "1.36"
pkl = "0.30"

# Web
node = "24"
pnpm = "10.29.3"

[tasks]
pre-commit = ["hk fix"]

web-dev = { dir = "web", run = "pnpm dev" }
web-lint = {dir = "web", run = "eslint" }
web-format = { dir = "web", run = "pnpm prettier" }
web-typecheck = { dir = "web", run = "pnpm typecheck" }
